### PR TITLE
Relax ordering requirements in rules programs

### LINKED ISSUE #284: Relax ordering requirements for declarations and statements in rule files; improve error messages
Example:
```
@source a[3]: load-csv("something.csv").
@declare a(integer, string, any).
```
gives error
```
Parse error on line 2, column 1: Syntax error: End of file
```

Expected behaviour:
Either accept the above, or something like
```
Parse error on line 2, column 1: Syntax error: @declare used after @source
```

### PR DESCRIPTION
**Pull request by mmarx**
Fixes #284.

### CODE REVIEW

**Review by matzemathics — APPROVED** [review]
Ok looks good. Maybe an end-to-end test would be nice?

File: nemo/src/io/parser.rs [hunk 1]
```diff
@@ -1611,4 +1659,42 @@ mod test {
...
+    #[test]
+    fn program_statement_order() {
+        assert_matches!(
+            parse_program(
+                r#"@output s .
+                   s(?s, ?p, ?o) :- t(?s, ?p, ?o) .
+                   @source t[3]: load-rdf("triples.nt") .
+                  "#
+            ),
+            Ok(_)
```
Comment (mmarx) [inline nemo/src/io/parser.rs:1672]: We have this, not sure if an end-to-end test would provide any additional value.

Comment (matzemathics) [reply nemo/src/io/parser.rs:1672]: yes very much much optional
