### PR TITLE
Replace deprecated rio with oxrdfio

### LINKED ISSUE #623: Malformed Prefixes in Turtle Files Cause Crashing
### Description  
Providing certain malformed `@prefix` directives in the resource file causes nemo to crash. 

### Steps to Reproduce  
1. `mwe.rls` file
    ```prolog
    @import TRIPLE :- turtle { resource = "triples.ttl" } .
    @export TRIPLE :- turtle {}.
    ```
2. `triples.ttl` file:  
    ```turtle
    # @prefix : <#>.
    # @prefix ont: <>.
    # @prefix riskm: <./>.
    @prefix owl: <http://www.w3.org/2002/07/owl#>.

    [ a owl:Ontology ] .
    ```
3. Uncomment any of the commented `@prefix` directives.  
4. Run `nmo mwe.rls`.

### PR DESCRIPTION
**Pull request by mmarx**
Replaces our dependency on the (deprecated by upstream) `rio` crates, in favour of `oxrdfio`. This also fixes #623, as `oxrdfio` is more robust in the face of malformed input.

### CODE REVIEW

File: nemo/src/io/formats/rdf/reader.rs [hunk 1]
```diff
@@ -184,7 +170,7 @@ impl RdfReader {
         let stop_limit = self.limit.unwrap_or(u64::MAX);
         let triple_count = Cell::new(0);
 
-        let mut on_triple = |triple: Triple| {
+        let mut on_triple = |triple: Quad| {
```
Comment (monsterkrampe) [inline nemo/src/io/formats/rdf/reader.rs:173]: Just double checking: `Triple` is `Quad` now?

Comment (mmarx) [reply nemo/src/io/formats/rdf/reader.rs:173]: Yes, `RdfParser` always iterates over Quads, since it doesn't know up front which format it will parse.

Comment (monsterkrampe) [reply nemo/src/io/formats/rdf/reader.rs:173]: Ok, then I think we should also rename variables accordingly to prevent confusion.

Comment (mmarx) [reply nemo/src/io/formats/rdf/reader.rs]: I hope this is clearer now.

**Review by monsterkrampe — APPROVED** [review]

File: nemo/src/io/formats/rdf/reader.rs (hunk 1 above)
Comment (monsterkrampe) [reply nemo/src/io/formats/rdf/reader.rs]: Thanks!
